# Generated by Django 5.2.4 on 2025-09-22 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('business', 'Business'), ('sports', 'Sports'), ('technology', 'Technology'), ('health', 'Health'), ('entertainment', 'Entertainment')], max_length=50)),
            ],
        ),
    ]
