# Generated by Django 5.2.6 on 2025-09-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('finance', 'Finance'), ('politics', 'Politics'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('science', 'Science')], max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
