# Generated by Django 5.2.4 on 2025-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_alter_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_type',
            field=models.CharField(choices=[('GLOBAL', 'Global News'), ('LOCAL', 'Local News')], default='GLOBAL', max_length=10),
        ),
    ]
