# Generated by Django 5.2.4 on 2025-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_news_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_type',
            field=models.CharField(choices=[('GLOBAL', 'Global News (General World)'), ('US_LOCAL', 'Local News (US)'), ('KERALA', 'Local News (Kerala)')], default='GLOBAL', max_length=10),
        ),
    ]
