# Generated by Django 5.2.4 on 2025-10-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_alter_news_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_type',
            field=models.CharField(choices=[('KERALA', 'Kerala News')], default='KERALA', max_length=10),
        ),
    ]
