# Generated by Django 5.2.4 on 2025-10-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_alter_news_source_type_readhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readhistory',
            options={'ordering': ['-read_at'], 'verbose_name_plural': ' History'},
        ),
    ]
